create table IF NOT EXISTS persons(
    id integer generated by default as identity,
    first_name varchar(255),
    last_name varchar (255),
    age integer,
    favourite_color varchar (255),
    primary key (id)
);
